name: phpcsfixer

on:
  push:
    paths:
      - '**.php'
      - '.php-cs-fixer.php.dist'
      - '.github/workflows/phpcsfixer.yml'

permissions:
  contents: write

jobs:
  phpcsfixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.bot_token }}
          persist-credentials: true
          ssh-strict: false

      - name: Force HTTPS remote for pushes
        run: |
          git remote set-url origin \
            https://x-access-token:${{ secrets.bot_token }}@github.com/${{ github.repository }}.git

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php.dist --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🎨 apply code styles [skip phpcsfixer]
          disable_globbing: true
          file_pattern: '*.php'
